# Generated by Django 4.0.4 on 2022-04-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=200)),
                ('types', models.TextField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gamers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.gamer')),
            ],
            options={
                'verbose_name_plural': 'games',
            },
        ),
    ]
