# Generated by Django 4.0.4 on 2022-04-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0003_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': 'loans'},
        ),
    ]
