# Generated by Django 4.0.4 on 2022-04-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0005_delete_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.RemoveField(
            model_name='game',
            name='gamers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='types',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.game')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.gamer')),
            ],
        ),
    ]
