# Generated by Django 4.0.4 on 2022-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0006_alter_game_options_remove_game_gamers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': 'loans'},
        ),
        migrations.AddField(
            model_name='loan',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
