# Generated by Django 4.0.4 on 2022-04-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0007_alter_loan_options_loan_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='game',
        ),
    ]
