# Generated by Django 4.0.4 on 2022-04-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0008_remove_loan_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='name',
        ),
    ]
